services:
  mysql:
    image: mysql:8.0
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  redis:
    image: redis:latest
    restart: "no"
    ports:
      - "6379:6379"
volumes:
  mysql_data:
